### ISSUE TITLE
Socket timeout Exception

### ISSUE THREAD

**Issue by Ramkesh9** [JessYanCoding/ProgressManager#52]
Hi Thank you for your library , download and glide start feature working properly, but a timeout error is coming again and again while click at "UPLOAD START". please address this issue, and help me to sort it out . i am attaching the logs, please look this once.

W/System.err: java.net.SocketTimeoutException: timeout
        at okio.Okio$4.newTimeoutException(Okio.java:232)
        at okio.AsyncTimeout.exit(AsyncTimeout.java:285)
W/System.err:     at okio.AsyncTimeout$1.write(AsyncTimeout.java:184)
        at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:179)
        at okio.RealBufferedSink.write(RealBufferedSink.java:42)
        at okhttp3.internal.http1.Http1Codec$FixedLengthSink.write(Http1Codec.java:295)
        at okio.ForwardingSink.write(ForwardingSink.java:35)
        at okhttp3.internal.http.CallServerInterceptor$CountingSink.write(CallServerInterceptor.java:149)
        at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:179)
        at okio.RealBufferedSink.write(RealBufferedSink.java:42)
        at okio.ForwardingSink.write(ForwardingSink.java:35)
        at me.jessyan.progressmanager.body.ProgressRequestBody$CountingSink.write(ProgressRequestBody.java:104)
        at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:179)
W/System.err:     at okio.RealBufferedSink.writeAll(RealBufferedSink.java:107)
        at okhttp3.RequestBody$3.writeTo(RequestBody.java:120)
        at me.jessyan.progressmanager.body.ProgressRequestBody.writeTo(ProgressRequestBody.java:81)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:72)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at me.jessyan.progressmanager.ProgressManager$1.intercept(ProgressManager.java:97)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
W/System.err:     at okhttp3.RealCall.execute(RealCall.java:77)
        at me.jessyan.progressmanager.demo.MainActivity$4.run(MainActivity.java:289)
        at java.lang.Thread.run(Thread.java:764)
    Caused by: java.net.SocketException: Socket closed
W/System.err:     at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:116)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
        at okio.Okio$1.write(Okio.java:79)
        at okio.AsyncTimeout$1.write(AsyncTimeout.java:180)
    	... 33 more
    java.net.SocketTimeoutException: timeout
W/System.err:     at okio.Okio$4.newTimeoutException(Okio.java:232)
        at okio.AsyncTimeout.exit(AsyncTimeout.java:285)
        at okio.AsyncTimeout$1.write(AsyncTimeout.java:184)
        at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:179)
        at okio.RealBufferedSink.write(RealBufferedSink.java:42)
        at okhttp3.internal.http1.Http1Codec$FixedLengthSink.write(Http1Codec.java:295)
        at okio.ForwardingSink.write(ForwardingSink.java:35)
        at okhttp3.internal.http.CallServerInterceptor$CountingSink.write(CallServerInterceptor.java:149)
        at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:179)
W/System.err:     at okio.RealBufferedSink.write(RealBufferedSink.java:42)

**Comment by JessYanCoding** [comment]
This is a server socket timeout and has no effect on the use of the library.

**Comment by Ramkesh9** [comment]
Thank you for respond, Socket timeout coming everytime without any success.
please let me know if i do tap at upload button without any modification at below url http://upload.qiniu.com/ 
then does it will work? 
or is their any changes required with url or any other place?

**Comment by Ramkesh9** [comment]
I fixed the socket timeout exception, 
Now upload progress bar uploading "A.java" file showing with proper  0 - 100% progress,
but A.java file is not visible anywhere at my server. 
so could you able to assist me with this concern?

**Comment by JessYanCoding** [comment]
ProgressManager can only show progress, the network request is the work of OkHttp, and has nothing to do with ProgressManager.
